SFP.SIT/src/SFP.SIT.WEB/Controllers/EstadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SFP.SIT.WEB.Services;
using SFP.SIT.WEB.Injection;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Hosting;
using SFP.SIT.WEB.Util;
using SFP.SIT.WEB.Models;
using SFP.SIT.AFD.Model;
using SFP.SIT.SERV.Dao;
using SFP.SIT.SERV.Util;
using SFP.SIT.SERV.Negocio;
using SFP.SIT.SERV.Dao.SOL;
using SFP.SIT.SERV.Dao.SNT;
using SFP.SIT.SERV.Model.SOL;
using SFP.SIT.AFD.Core;
using SFP.SIT.SERV.Dao.RED;
using SFP.SIT.SERV.Model.RED;
using System.Data;
using SFP.SIT.SERV.Dao.RESP;
using SFP.SIT.SERV.Model.DOC;
using SFP.SIT.SERV.Model.RESP;
using SFP.SIT.SERV.Model._Consultas;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace SFP.SIT.WEB.Controllers
{
    public class EstadoController : SitBaseCtlr
    {
        SolicitudSer _solServ;

        public EstadoController(ICacheWebSIT memCache, IHttpContextAccessor httpContextAccessor, ILogger<EstadoController> logger, IHostingEnvironment app)
            : base(memCache, httpContextAccessor, logger, app)
        {
            _iUsuario = Convert.ToInt32(_httpContextAccessor.HttpContext.User.FindFirst(ConstantesWeb.Usuario.CLAVE).Value);
            _solServ = new SolicitudSer(_sitDmlDbSer);
        }


        private string DelimitarPlazo(AfdEdoPdoMdl edoAccionMdl, DateTime solFecha, ref CalcularPlazoNeg calcularPlazoNeg)
        {           
            DateTime dtFechaLimite = calcularPlazoNeg.ObtenerFechaFinal(solFecha, edoAccionMdl.plazo);
            //dtFechaLimite.ToString("yyyy/MM/dd");
            return "2018/12/31";
        }

        public EdoActViewModel ObtenerDatosGral(long nodo, bool bSolicitante, int iPrc, int iArea, int iPerfil)
        {
            EdoActViewModel edoActVM = new EdoActViewModel();
            DateTime dteFecAclaracion = new DateTime();
            

            SIT_RED_NODO redNodo = _sitDmlDbSer.operEjecutar<SIT_RED_NODODao>(nameof(SIT_RED_NODODao.dmlSelectNodoID), nodo) as SIT_RED_NODO;
            CalcularPlazoNeg calcularPlazoNeg = new CalcularPlazoNeg(_memCacheSIT.ObtenerDato(CacheWebSIT.DIC_DIA_NO_LABORAL) as Dictionary<Int64, char>);
            SIT_SOL_SOLICITUD solSolicitud = _sitDmlDbSer.operEjecutar<SIT_SOL_SOLICITUDDao>(nameof(SIT_SOL_SOLICITUDDao.dmlSelectID),
                new SIT_SOL_SOLICITUD { solclave = (long)redNodo.solclave }) as SIT_SOL_SOLICITUD;

            edoActVM.folio = solSolicitud.solclave;
            edoActVM.solFecIni = solSolicitud.solfecrec.ToString("dd/MM/yyyy");
            edoActVM.solFecIniTicks = solSolicitud.solfecsol.Ticks;
            edoActVM.solTipo = (int)solSolicitud.sotclave;
            edoActVM.nodClave = nodo;
            edoActVM.perClave = iPerfil;
            edoActVM.fecIni = "new Date('" + solSolicitud.solfecrec.ToString("yyyy/MM/dd") + "')";
            edoActVM.fecAct = "new Date('" + DateTime.Now.ToString("yyyy/MM/dd") + "')";
            edoActVM.araClave = (int)redNodo.araclave;

            /* INICIO VALORES PANEL IZQUIERDO     */
            // SOLICITANTE
            if (bSolicitante)
                edoActVM.solicitante = JsonTransform.convertJson(
                    _sitDmlDbSer.operEjecutar<SIT_SNT_SOLICITANTEDao>(nameof(SIT_SNT_SOLICITANTEDao.dmlSelectSolicitanteTranspuestoPorID), solSolicitud.solclave) as DataTable);
            else
                edoActVM.solicitante = JsonTransform.NO_RECORDS;

            //SOLICTUD
            edoActVM.solicitud = _solServ.ObtenerSolicitudTranspuesta(solSolicitud.solclave, out dteFecAclaracion);

            // ACLARACION
            SIT_SOL_SEGUIMIENTO segAclMdl = _solServ.ObtenerSeguimiento(edoActVM.folio, Constantes.ProcesoTipo.ACLARACION);
            if (dteFecAclaracion != DateTime.MinValue)
                edoActVM.aclaracion = _solServ.ObtenerAclaracion(edoActVM.folio,
                    Constantes.Respuesta.REQ_INFO_ADICIONAL, Constantes.Respuesta.RECEPCION_INFO_ADICIONAL);
            else
                edoActVM.aclaracion = JsonTransform.NO_RECORDS;

            // RECURSO DE REVISION
            edoActVM.recRevision = _solServ.ObtenerRecRevision(solSolicitud.solclave);
            /* FIN VALORES PANEL IZQUIERDO     */

            /* ACTUALIZAR LA LISTA DE ACCIONES  */
            Dictionary<Int32, AfdNodoFlujo> dicFlujoTrabajo = _memCacheSIT.ObtenerDato(CacheWebSIT.DIC_AFD_FLUJO) as Dictionary<Int32, AfdNodoFlujo>;
            AfdNodoFlujo NodoFlujo = dicFlujoTrabajo[(int)redNodo.nedclave];

            List<AfdEdoPdoMdl> lstEdoAccion = new List<AfdEdoPdoMdl>();
            foreach (KeyValuePair<int, AfdEdoPdoMdl> pair in NodoFlujo.DicAristaPlazo)
                lstEdoAccion.Add(pair.Value);

            AfdEdoPdoMdl edoQuitarTurnar = null;
            AfdEdoPdoMdl edoQuitarAmpliacion = null;

            edoActVM.turnarTransp = JsonTransform.NO_RECORDS;
            edoActVM.turnarArea = JsonTransform.NO_RECORDS;
            edoActVM.turnarAreasInternas = JsonTransform.NO_RECORDS;

            foreach (AfdEdoPdoMdl edoAccionMdl in lstEdoAccion)
            {
                if (edoAccionMdl.plazo > 0)
                {
                    edoAccionMdl.fecLimite = DelimitarPlazo(edoAccionMdl, solSolicitud.solfecrec, ref calcularPlazoNeg);
                }


                if (edoAccionMdl.id == Constantes.Respuesta.ASIGNAR)
                {
                    Dictionary<string, object> dicParam = new Dictionary<string, object>();
                    dicParam.Add(Constantes.Parametro.FECHA, DateTime.Now);
                    dicParam.Add(DButil.SIT_ADM_PERFIL_COL.PERCLAVE, Constantes.Perfil.PRUT);

                    edoActVM.turnarTransp = JsonTransform.convertJson(_sitDmlDbSer.operEjecutar<ConsultaDao>(nameof(ConsultaDao.dmlSelectPersonasPerfil), dicParam));

                    if (edoActVM.turnarTransp == JsonTransform.NO_RECORDS)
                        edoQuitarTurnar = edoAccionMdl;
                }
                else if (edoAccionMdl.id == Constantes.Respuesta.TURNAR)
                {
                    Dictionary<string, object> dicParam = new Dictionary<string, object>();
                    dicParam.Add(Constantes.Parametro.FECHA, DateTime.Now);
                    dicParam.Add(DButil.SIT_ADM_AREAHIST_COL.ARHREPORTA, iArea);

                    if (iPerfil == Constantes.Perfil.UA)
                    {
                        edoActVM.turnarAreasInternas = JsonTransform.convertJson(_sitDmlDbSer.operEjecutar<ConsultaDao>(nameof(ConsultaDao.dmlSelectAreasActualReporta), dicParam));
                        if (edoActVM.turnarAreasInternas == JsonTransform.NO_RECORDS)
                            edoQuitarTurnar = edoAccionMdl;
                    }
                    else
                    {
                        edoActVM.turnarArea = JsonTransform.convertJson(_sitDmlDbSer.operEjecutar<ConsultaDao>(nameof(ConsultaDao.dmlSelectAreasActual), DateTime.Now));
                        if (edoActVM.turnarArea == JsonTransform.NO_RECORDS)
                            edoQuitarTurnar = edoAccionMdl;
                    }
                }

                else if (edoAccionMdl.id == Constantes.Respuesta.AMPLIACION_PLAZO)
                {
                    if (segAclMdl != null)
                        edoQuitarAmpliacion = edoAccionMdl;
                }

                else if (edoAccionMdl.id == Constantes.Respuesta.RESPUESTA_MULTIPLE)
                {
                    edoActVM.lstEdoSubAccion = new List<AfdEdoPdoMdl>();
                    List<SIT_RESP_TIPO> lstResptipo = _sitDmlDbSer.operEjecutar<SIT_RESP_TIPODao>(nameof(SIT_RESP_TIPODao.dmlSelectRespTipoLst), 6) as List<SIT_RESP_TIPO>;
                    for (int iIdxResp = 0; iIdxResp < lstResptipo.Count; iIdxResp++)
                    {
                        AfdEdoPdoMdl edoSubAccionMdl = new AfdEdoPdoMdl
                        {
                            id = lstResptipo[iIdxResp].rtpclave,
                            plazo = lstResptipo[iIdxResp].rtpplazo,
                            fecLimite = "",
                            forma = lstResptipo[iIdxResp].rtpforma,
                            nivel = lstResptipo[iIdxResp].rtptipo,
                            formato = lstResptipo[iIdxResp].rtpformato,
                            text = lstResptipo[iIdxResp].rtpdescripcion
                        };

                        if (lstResptipo[iIdxResp].rtpplazo > 0)
                        {
                            edoSubAccionMdl.fecLimite = DelimitarPlazo(edoSubAccionMdl, solSolicitud.solfecrec, ref calcularPlazoNeg);
                        }
                        edoActVM.lstEdoSubAccion.Add(edoSubAccionMdl);
                    }
                }
            }

            if (edoQuitarTurnar != null)
                lstEdoAccion.Remove(edoQuitarTurnar);

            if (edoQuitarAmpliacion != null)
                lstEdoAccion.Remove(edoQuitarAmpliacion);

            lstEdoAccion.Sort(delegate (AfdEdoPdoMdl x, AfdEdoPdoMdl y)
            {
                if (x.text == null && y.text == null) return 0;
                else if (x.text == null) return -1;
                else if (y.text == null) return 1;
                else return x.text.CompareTo(y.text);
            });
            edoActVM.lstEdoAccion = lstEdoAccion;
            edoActVM.listaAccion = JsonTransform.convertJson(lstEdoAccion);
            edoActVM.listaSubAccion = JsonTransform.convertJson(edoActVM.lstEdoSubAccion);
                

            edoActVM.controlName = "Flujo" + _memCacheSIT.ObtenerDato(CacheWebSIT.DIC_AFD_FLUJO).ToString();
            edoActVM.tipoPrcActual = iPrc;
            

            // AQUI COLOCO EL TITULO Y SU BUSQUEDA....
            String sProceso = _memCacheSIT.BuscarLista(CacheWebSIT.LST_SOL_PROCESO, iPrc.ToString());

SFP.SIT/src/SFP.SIT.WEB/Views/Estado/Edonew.cshtml
@{    Layout = "~/Views/Shared/_LayoutBase.cshtml";}

<div id="divMain" style="padding-left:10px; margin-top:2px; margin-bottom:2px;">
    <div class="w2ui-field w2ui-span6" style="clear: both">
        <label>Acción a realizar :</label>
        <div>
            <select id="lstAccion" style="float: left; width:450px;"> </select>
        </div>
    </div>

    <div class="w2ui-field w2ui-span6" style="clear: both">
        <label>Instrucciones :</label>
        <div>
            <div id="divInstr" style="background-color:white; height:65px; width:99%; overflow:auto; margin-top:5px; margin-left:5px; display:inline-block">
                @Html.Raw(ViewBag.Instruccion)
            </div>
        </div>
    </div>
</div>

<div id="layoutTopMain" style="height:99%;"> </div>

@section Scripts
    {
    <script>
    var _PaginaActual;

    _ListaAccion = @Html.Raw(ViewBag.ListaAccion);

    $(function () {
        w2ui['layoutMain'].content('main',
            {
                render: function ()
                {
                    $(this.box).append($('#layoutTopMain').detach());
                    $('#layoutTopMain').w2layout(GetLayoutTopMain("130px", "70%"));

                    @*--PANEL TOP -- *@
                    w2ui['layoutTopMain'].content('top', {
                        render: function () {
                            $(this.box).append($('#divMain').detach());
                            SelectAddElemClearLimite("lstAccion", _ListaAccion, _solfecsol, _FechaAct, 0);
                        }
                    });

                    $('#lstAccion').change(function () {
                        if ($('#lstAccion').val() != null) {
                            _PaginaActual = _UrlRespuesta + AristaClick(_ListaAccion, parseInt($('#lstAccion').val())) + "?solclave=" + _solclave + "&proclave=" + _proclave + "&nodclave=" + _nodclave;

                            AjaxValidarSesion(_UrlSesionActiva, _UrlInicio);

                            w2ui['layoutTopMain'].load('main', _PaginaActual, null, function () {
                                $("#btnAccion").remove();
                                $('#divMenuAccion').append("<a id='btnAccion' name='btnAccion'> <div class='boton2'><div class='num4'></div></div> </a> ");
                                Inicializar();
                                $('#btnAccion').click(Grabar);
                                $('#avanzar').val(1);
                            });
                        }
                    });

                }
            }
        );
    });
    </script>
}

SFP.SIT/src/SFP.SIT.WEB/Views/Estado/PRUDrecibirsol.cshtml
@{
    Layout = "~/Views/Shared/_LayoutBase.cshtml";
}

<div id="divMain" style="padding-left:10px; margin-top:2px; margin-bottom:2px;">
    <div class="w2ui-field w2ui-span6" style="clear: both">
        <label>Acción a realizar :</label>
        <div>
            <select id="lstAccion" style="float: left; width:450px;"> </select>
        </div>
    </div>

    <div class="w2ui-field w2ui-span6" style="clear: both">
        <label>Instrucciones :</label>
        <div>
            <div id="divInstr" style="background-color:white; height:65px; width:99%; overflow:auto; margin-top:5px; margin-left:5px; display:inline-block">
                @Html.Raw(ViewBag.Instruccion)
            </div>
        </div>
    </div>
</div>

<div id="layoutTopMain" style="height:99%; "> </div>

@section Scripts
    {
        <script>
        var _PaginaActual;

        _ListaAccion = @Html.Raw(ViewBag.ListaAccion);

        $(function () {
            w2ui['layoutMain'].content('main',
                {
                    render: function ()
                    {
                        $(this.box).append($('#layoutTopMain').detach());
                        $('#layoutTopMain').w2layout(GetLayoutTopMain("130px", "70%"));

                        @*--PANEL TOP -- *@
                        w2ui['layoutTopMain'].content('top', {
                            render: function () {
                                $(this.box).append($('#divMain').detach());
                                SelectAddElemClearLimite("lstAccion", _ListaAccion, _solfecsol, _FechaAct, 0);
                            }
                        });

                        $('#lstAccion').change(function () {
                            if ($('#lstAccion').val() != null) {
                                _PaginaActual = _UrlRespuesta + AristaClick(_ListaAccion, parseInt($('#lstAccion').val())) + "?solclave=" + _solclave + "&proclave=" + _proclave + "&nodclave=" + _nodclave;

                                AjaxValidarSesion(_UrlSesionActiva, _UrlInicio);

                                w2ui['layoutTopMain'].load('main', _PaginaActual, null, function () {
                                    $("#btnAccion").remove();
                                    $('#divMenuAccion').append("<a id='btnAccion' name='btnAccion'> <div class='boton2'><div class='num4'></div></div> </a> ");
                                    Inicializar();
                                    $('#btnAccion').click(GrabarIFrame);
                                    $('#avanzar').val(1);
                                });
                            }
                        });

                    }
                }
            );
        });

        function Actualizar(event) {
            if (_Inicio == false) {
                Responder();
            }
        }

    </script>
}

SFP.SIT/src/SFP.SIT.WEB/Views/Estado/UAanalizarSol.cshtml
@{
    Layout = "~/Views/Shared/_LayoutBase.cshtml";
}

<div id="divMensaje">
    <div>
        <label style="margin-left:10px;">Instrucciones internas acerca de la solicitud</label>
        @if (ViewBag.Archivo != null)
        {
            <a id="aDoc" asp-controller="Estado" asp-action="Documento" asp-route-id="@ViewBag.Archivo" class="glyphicon glyphicon glyphicon-list-alt btn-lg" data-toggle="tooltip" title="Ver documento anexo" target="_blank" style="margin-left:15px; ">Archivo Anexo</a>
        }
    </div>
    <div id="divInstr" style="background-color:white; height:110px; width:99%; overflow:auto; margin-top:5px; margin-left:5px; display:inline-block"></div>

    <div id="tab-example">
        <div id="tabs" style="width: 100%; height: 29px;"></div>
        <div id="Datos" style="width: 100%; height: 200px;"></div>
    </div>

    <form id="frmBorrar" asp-controller="Estado" asp-action="UAanalizarBorrar" method="post" accept-charset="UTF-8">
        @Html.AntiForgeryToken()
        <input type="hidden" id="repclave" name="repclave">
        <input type="hidden" id="rtpclave" name="rtpclave">
        <input type="hidden" id="nodClave" name="nodClave">
    </form>

</div>

<!-- FORMA MODAL-->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content" style="background-color:whitesmoke;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div id="divTopLista" class="w2ui-span10" style="padding-left:10px; margin-bottom:2px;">
                    <div id="divTopListaTiulo" style="float:left; font-family:'Roboto', sans-serif; font-size:14px; font-weight:bold; color:#666;"></div>
                    <div id="divlstAccion" style="float:left; margin-left:20px; "><select id="lstAccion" style="float:left;"> </select> </div>
                </div>
            </div>
            <div id="divBody" class="modal-body">
                <div id="divResMultiple" style="overflow: auto; height:580px; "> </div>
            </div>
            <div class="modal-footer">
                <button id="btnAnalizarCerrar" type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button id="btnAnalizarGrabar" name="btnAnalizarGrabar" type="button" class="btn btn-default">Grabar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        var _Instr = "@Html.Raw( ViewBag.Instruccion)";

        var _FormaBorrar = null;
        var _ResultadoOper = 0;
        

        _ListaAccion = @Html.Raw(ViewBag.ListaAccion);
        var _ListaSubAccion = @Html.Raw(ViewBag.ListaSubAccion);

        var config = {
            tabs: {
                name: 'tabs',
                tabs: [
                    { id: 'tab1', caption: 'Revisar Respuesta(s) de UA(s)' }
                ],
                onClick: function (event) {
                    $('#tab-example .tab').hide();
                    $('#tab-example #' + event.target).show();

                    $('#btnResponder').remove();
                    $('#divMenuAccion').append("<a id='btnResponder' name='btnResponder' data-toggle='tooltip' title='Responder solicitud' class='btn btn-success btn-lg btn-block btn-circle col-xs-12 glyphicon glyphicon-cog' style='font-size: 25px;  float:right; width:40px; height:40px;' > </a> ")

                    var TabID = 0;
                    for (var iIdx = 0; iIdx < _ListaAccion.records.length; iIdx++) {
                        _rtpClave = _ListaAccion.records[iIdx].id;

                        if (event.target == ("tab-" + _rtpClave)) {

                            $("#rtpclave").val(_rtpClave);

                            var urlForma = _UrlRespuesta + _ListaAccion.records[iIdx].forma + "?solclave=" + _solclave + "&proclave=" + _proclave + "&nodclave=" + _nodclave + "&Oper=1";
                            $("#Datos").empty();
                            $("#Datos").load(urlForma, function () {
                                Inicializar();

                                // multiple
                                if (event.target != 'tab-22') {
                                    document.getElementById("btnResponder").addEventListener('click', GrabarIFrame);
                                }
                                else {
                                    if (w2ui.gridUArespuesta.records.length == 0) {
                                        $('#btnResponder').hide();
                                    }
                                    document.getElementById("btnResponder").addEventListener('click', function () { w2alert("Hol amak") });
                                    // solo avanza
                                }
                            });
                       
                        }
                    }
                }
            }
        }

        function CrearTabs() {
            var oTabs = [];
            for (var iIdx = 0; iIdx < _ListaAccion.records.length; iIdx++) {
                oTabs.push({ id: 'tab-' + _ListaAccion.records[iIdx].id, caption: _ListaAccion.records[iIdx].text, class: "tab" });
            }
            config.tabs.tabs = oTabs;
            $('#tabs').w2tabs(config.tabs);
        }

        $(document).ready(function () {
            w2ui['layoutMain'].content('main', {
                render: function () {
                    $(this.box).append($('#divMensaje').detach());
                    $("#divInstr").text(_Instr);
                    CrearTabs();
                }
            });

            $('#myModal').on('hidden.bs.modal', function (e) {
                window.location.reload();
            })
        });


        function Actualizar(event) {            
            if (_Inicio == false)
            {
                //Si es multiple actualizamos GRID 
                if (_rtpClave == 22)
                {
                    _Inicio = false;
                    $('#myModal').modal('toggle');
                    window.location.reload();                    
                }
                else
                { 
                    Responder(); 
                }
            }
        }

    /* ------------------------------------
            AQUI VIENE EL GRID
    --------------------------------------- */
        function ActualizarGrid(data)
        {
            if (data === '1') {
                w2ui.gridUArespuesta.delete(true);
                Continuar();
            }
        }


        function GuardarRespOnclick(event) {
            event.done(function () {
                if (Grabar() == true)
                    w2popup.close()
                else
                    w2alert("El registro no fue almacenado");
            });
        }

        function SelectAddElemReserva(nombre, elementos) {
            // Primero borramos contenido
            $('#' + nombre)
                .find('option')
                .remove()
                .end();

            $('#' + nombre).append($('<option>', {
                value: 0,
                text: " -- Seleccionar --",
                ///disabled: "disabled",
                selected: "selected"
            }));

            for (var iIdx = 0; iIdx < elementos.records.length; iIdx++) {
                // ESTADO 3 ES  UNA PROPUESTA o NEGADO.,..
                if (elementos.records[iIdx].sdoClaveActual == 3) {
                    $('#' + nombre).append($('<option>', {
                        value: elementos.records[iIdx].repclave,
                        text: elementos.records[iIdx].rsvexpediente,
                        disabled: "disabled"
                    }));
                } else {
                    $('#' + nombre).append($('<option>', {
                        value: elementos.records[iIdx].repclave,
                        text: elementos.records[iIdx].rsvexpediente
                    }));
                }
            }
        }

        function ValorMaxGrid( sNombreGrid ) {
            var iMaxActual = 0;
            var iRecIdActual = 0;

            for (var iIdx = 0; iIdx < w2ui[sNombreGrid].records.length; iIdx++)
            {
                iRecIdActual = w2ui[sNombreGrid].records[iIdx].recid;
                if (iRecIdActual > iMaxActual)
                {
                    iMaxActual = iRecIdActual;
                }
            }
            return iMaxActual + 1;
        }

        function FormItemGrid()
        {
            var archivoSel = document.getElementById("docTipoDato").files[0];
            var iMaxRecID = ValorMaxGrid('gridConfidencial');

            if (archivoSel != undefined) {
                if (archivoSel.size > 5242880) {
                    w2alert("El tamaño del archivo es mayor a 5MB");
                    return;
                }

                w2ui['gridConfidencial'].add([{
                    recid: iMaxRecID, repclave: $("#resRespuesta_repclave").val(),
                    detclave: $("#txtClave").val(), detdescripcion: $("#txtDescripcion").val(), docclave: 0,
                    docTemp: archivoSel.name
                }]);
                validatedFiles.push(archivoSel);
            } else {
                w2ui['gridConfidencial'].add([{
                    recid: iMaxRecID, repclave: $("#resRespuesta_repclave").val(),
                    detclave: $("#txtClave").val(), detdescripcion: $("#txtDescripcion").val(), docclave: 0
                }]);
            }
            Ocultar();
        }

        function Mensaje() {
            getBase64(validatedFiles[0]);
        }

        function getBase64(file) {
            var reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = function () {
                var ventana = window.open("#", "_blank");
                ventana.document.write('<html><title>Visualizar documento</title><body style="margin-top:0px; margin-left:0px;margin-right:0px;margin-bottom:0px;">');
                ventana.document.write('<iframe type="application/pdf" height="100%" width="100%" src="' + reader.result + '"> </iframe>');
                ventana.document.write('</body></html>');
            };
            reader.onerror = function (error) {
                w2alert("error");
            };
        }

    </script>
}

SFP.SIT/src/SFP.SIT.WEB/Views/Estado/UTrecibirSol.cshtml
@{
    Layout = "~/Views/Shared/_LayoutBase.cshtml";
}

<div id="divMain" style="padding-left:10px; margin-top:2px; margin-bottom:2px;">
    <div class="w2ui-field w2ui-span6" style="clear: both">
        <label>Acción a realizar :</label>
        <div>
            <select id="lstAccion" style="float: left; width:450px;"> </select>
        </div>
    </div>
</div>

<div id="layoutTopMain" style="height:99%;"> </div>

@section Scripts
    {
    <script>
        var _PaginaActual;

        _ListaAccion = @Html.Raw(ViewBag.ListaAccion);

        $(function () {
            w2ui['layoutMain'].content('main',
                {
                    render: function ()
                    {
                        $(this.box).append($('#layoutTopMain').detach());
                        $('#layoutTopMain').w2layout(GetLayoutTopMain("45px", "80%"));

                        @*--PANEL TOP -- *@
                        w2ui['layoutTopMain'].content('top', {
                            render: function () {
                                $(this.box).append($('#divMain').detach());
                                SelectAddElemClearLimite("lstAccion", _ListaAccion, _solfecsol, _FechaAct);
                            }
                        });

                        $('#lstAccion').change(function () {
                            if ($('#lstAccion').val() != null) {
                                _PaginaActual = _UrlRespuesta + AristaClick(_ListaAccion, parseInt($('#lstAccion').val())) + "?solclave=" + _solclave + "&proclave=" + _proclave + "&nodclave=" + _nodclave;

                                AjaxValidarSesion(_UrlSesionActiva, _UrlInicio);

                                w2ui['layoutTopMain'].load('main', _PaginaActual, null, function () {
                                    $("#btnAccion").remove();
                                    $('#divMenuAccion').append("<a id='btnAccion' name='btnAccion'> <div class='boton2'><div class='num4'></div></div> </a> ");
                                    $('#btnAccion').click(GrabarIFrame);
                                    Inicializar();                                
                                    $('#avanzar').val(1);
                                });
                            }
                        });
                    }
                }
            );
        });

        function Actualizar(event) {
            if (_Inicio == false)
            { 
                Responder();        
            }            
        }

    </script>
}